revoke all on function public.assign_corrective_action_reference() from anon, authenticated;
revoke all on function public.can_create_corrective_action(uuid) from anon;
revoke all on function public.can_manage_corrective_action(uuid, uuid) from anon;
revoke all on function public.can_manage_investigation_content(uuid, uuid) from anon;
revoke all on function public.can_verify_corrective_action(uuid, uuid) from anon;
revoke all on function public.can_view_corrective_action(uuid, uuid) from anon;
revoke all on function public.close_incident(uuid) from anon;
revoke all on function public.create_corrective_action(uuid, uuid, text, text, text, public.corrective_action_priority, uuid, date) from anon;
revoke all on function public.create_investigation(uuid, uuid, uuid, date) from anon;
revoke all on function public.list_organization_invitations() from anon;
revoke all on function public.next_corrective_action_reference(uuid) from anon, authenticated;
revoke all on function public.record_investigation_activity(uuid, uuid, text, jsonb) from anon;
revoke all on function public.record_workflow_event(uuid, text, text, text, uuid, uuid, jsonb, text) from anon;
revoke all on function public.submit_corrective_action_for_verification(uuid) from anon;
revoke all on function public.transition_incident_status(uuid, public.incident_status) from anon;
revoke all on function public.update_corrective_action_status(uuid, public.corrective_action_status) from anon;
revoke all on function public.verify_corrective_action(uuid, boolean, text) from anon;

revoke all on table public.investigation_correction_evidence from anon;
revoke all on table public.investigation_corrections from anon;
revoke all on table public.investigation_findings from anon;
revoke all on table public.investigation_root_causes from anon;

revoke all on function public.assign_corrective_action_reference() from public;
revoke all on function public.can_create_corrective_action(uuid) from public;
revoke all on function public.can_manage_corrective_action(uuid, uuid) from public;
revoke all on function public.can_manage_investigation_content(uuid, uuid) from public;
revoke all on function public.can_verify_corrective_action(uuid, uuid) from public;
revoke all on function public.can_view_corrective_action(uuid, uuid) from public;
revoke all on function public.close_incident(uuid) from public;
revoke all on function public.create_corrective_action(uuid, uuid, text, text, text, public.corrective_action_priority, uuid, date) from public;
revoke all on function public.create_investigation(uuid, uuid, uuid, date) from public;
revoke all on function public.list_organization_invitations() from public;
revoke all on function public.next_corrective_action_reference(uuid) from public;
revoke all on function public.record_investigation_activity(uuid, uuid, text, jsonb) from public;
revoke all on function public.record_workflow_event(uuid, text, text, text, uuid, uuid, jsonb, text) from public;
revoke all on function public.submit_corrective_action_for_verification(uuid) from public;
revoke all on function public.transition_incident_status(uuid, public.incident_status) from public;
revoke all on function public.update_corrective_action_status(uuid, public.corrective_action_status) from public;
revoke all on function public.verify_corrective_action(uuid, boolean, text) from public;